---
parameters:
  - name: targetSuffix
    type: string
  - name: armClientId
    type: string
  - name: armClientSecret
    type: string
  - name: armTenantId
    type: string
  - name: armSubscriptionId
    type: string

steps:
  #retrieve app service status endpoints
  - bash: |
      az login --service-principal -u $clientId -p $clientSecret --tenant $tenantId
      az account set --subscription $subscriptionId
      coordinatorLocation=https://$(az webapp config hostname list --webapp-name $coordinatorAppName --resource-group $pipelineResourceGroup --query '[0].name' -o tsv)
      pdfGeneratorLocation=https://$(az webapp config hostname list --webapp-name $pdfGeneratorAppName --resource-group $pipelineResourceGroup --query '[0].name' -o tsv)
      pdfRedactorLocation=https://$(az webapp config hostname list --webapp-name $pdfRedactorAppName --resource-group $pipelineResourceGroup --query '[0].name' -o tsv)
      textExtractorLocation=https://$(az webapp config hostname list --webapp-name $textExtractorAppName --resource-group $pipelineResourceGroup --query '[0].name' -o tsv)
      tempExtractorLocation=https://$(az webapp config hostname list --webapp-name $tempExtractorAppName --resource-group $pipelineResourceGroup --query '[0].name' -o tsv)
      gatewayLocation=https://$(az webapp config hostname list --webapp-name $gatewayAppName --resource-group $uiResourceGroup --query '[0].name' -o tsv)
      spaLocation=https://$(az webapp config hostname list --webapp-name $spaAppName --resource-group $uiResourceGroup --query '[0].name' -o tsv)
      proxyLocation=https://$(az webapp config hostname list --webapp-name $proxyAppName --resource-group $uiResourceGroup --query '[0].name' -o tsv)
      
      echo "##vso[task.setvariable variable=coordinatorUri;isOutput=true]$coordinatorLocation"
      echo "##vso[task.setvariable variable=pdfGeneratorUri;isOutput=true]$pdfGeneratorLocation"
      echo "##vso[task.setvariable variable=pdfRedactorUri;isOutput=true]$pdfRedactorLocation"
      echo "##vso[task.setvariable variable=textExtractorUri;isOutput=true]$textExtractorLocation"
      echo "##vso[task.setvariable variable=tempExtractorUri;isOutput=true]$tempExtractorLocation"
      echo "##vso[task.setvariable variable=gatewayUri;isOutput=true]$gatewayLocation"
      echo "##vso[task.setvariable variable=spaUri;isOutput=true]$spaLocation"
      echo "##vso[task.setvariable variable=proxyUri;isOutput=true]$proxyLocation"
    displayName: Get URIs of Polaris Components
    name: uris
    env:
      clientId: ${{ parameters.armClientId }}
      clientSecret: ${{ parameters.armClientSecret }}
      tenantId: ${{ parameters.armTenantId }}
      subscriptionId: ${{ parameters.armSubscriptionId }}
      coordinatorAppName: "fa-polaris${{ parameters.targetSuffix }}-coordinator"
      pdfGeneratorAppName: "fa-polaris${{ parameters.targetSuffix }}-pdf-generator"
      pdfRedactorAppName: "fa-polaris${{ parameters.targetSuffix }}-pdf-redactor"
      textExtractorAppName: "fa-polaris${{ parameters.targetSuffix }}-text-extractor"
      tempExtractorAppName: "fa-polaris${{ parameters.targetSuffix }}-temp-extractor"
      gatewayAppName: "fa-polaris${{ parameters.targetSuffix }}-gateway"
      spaAppName: "as-web-polaris${{ parameters.targetSuffix }}"
      pipelineResourceGroup: "rg-polaris-pipeline${{ parameters.targetSuffix }}"
      uiResourceGroup: "rg-polaris${{ parameters.targetSuffix }}"
      proxyAppName: "polaris${{ parameters.targetSuffix}}-cmsproxy"
